# This file was generated by GoReleaser. DO NOT EDIT.
cask "catalyst" do
  name "catalyst"
  desc "CLI tool for controlling Nature Remo devices"
  homepage "https://github.com/Eagle-Konbu/catalyst"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "catalyst"

  on_macos do
    on_intel do
      url "https://github.com/Eagle-Konbu/catalyst/releases/download/v#{version}/catalyst_#{version}_darwin_amd64.tar.gz"
      sha256 "d1cd15ae08006a96a228c77f4ede9ab1ccd767c0bca31d91ad8793912f058b88"
    end
    on_arm do
      url "https://github.com/Eagle-Konbu/catalyst/releases/download/v#{version}/catalyst_#{version}_darwin_arm64.tar.gz"
      sha256 "00d8065beaf9efa4954187f8cee53039669aaaee925d6fffbdd6a97aeb834cd7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Eagle-Konbu/catalyst/releases/download/v#{version}/catalyst_#{version}_linux_amd64.tar.gz"
      sha256 "52a28e1458bb50daa025d7f9d204f5d095fa13cbd8d75c769c3ea06e782d4625"
    end
    on_arm do
      url "https://github.com/Eagle-Konbu/catalyst/releases/download/v#{version}/catalyst_#{version}_linux_arm64.tar.gz"
      sha256 "7d5110eedb9d98dd64ffbee6a9476b90f3052f2281552e98ac99e1c2cfc824aa"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/catalyst"]
    end
  end

  # No zap stanza required
end
