# This file was generated by GoReleaser. DO NOT EDIT.
cask "sanat" do
  version "1.0.0-alpha.1"

  on_macos do
    on_intel do
      sha256 "05dfce4bbc08941ca6eeeb00e4f73fab690e6b6bda3776894d47931780a82468"
      url "https://github.com/Eagle-Konbu/sanat/releases/download/v#{version}/sanat_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5f19c34ef0e3ba15d0d2861d33969f1bb20abcbc8e3016fa82a99548b823a54"
      url "https://github.com/Eagle-Konbu/sanat/releases/download/v#{version}/sanat_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "77da7cdb467d3df9fd547912b97a9fde882c62f4b2a2521e0789c8cda58c494f"
      url "https://github.com/Eagle-Konbu/sanat/releases/download/v#{version}/sanat_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff8331757dc457ecd756903bdd227eed2df77fa88aaa5607dea71874f1df1f29"
      url "https://github.com/Eagle-Konbu/sanat/releases/download/v#{version}/sanat_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sanat"
  desc "Yet another CLI tool that automatically formats embedded SQL literals in Go source files"
  homepage "https://github.com/Eagle-Konbu/sanat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sanat"
  bash_completion "completions/sanat.bash"
  fish_completion "completions/sanat.fish"
  zsh_completion "completions/_sanat"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sanat"]
    end
  end

  # No zap stanza required

end
