# This file was generated by GoReleaser. DO NOT EDIT.
cask "sanat" do
  name "sanat"
  desc "Yet another CLI tool that automatically formats embedded SQL literals in Go source files"
  homepage "https://github.com/Eagle-Konbu/sanat"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sanat"
  bash_completion "completions/sanat.bash"
  zsh_completion "completions/_sanat"
  fish_completion "completions/sanat.fish"

  on_macos do
    on_intel do
      url "https://github.com/Eagle-Konbu/sanat/releases/download/v#{version}/sanat_#{version}_darwin_amd64.tar.gz"
      sha256 "2c120142a038c21ec825c1b2a7f7d023157cf8b59e707fa06b3bd1aa4c99d518"
    end
    on_arm do
      url "https://github.com/Eagle-Konbu/sanat/releases/download/v#{version}/sanat_#{version}_darwin_arm64.tar.gz"
      sha256 "1e3789f8dc25e3960dc8630f1a8c5032659d781410c78faab3d522b01093385d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Eagle-Konbu/sanat/releases/download/v#{version}/sanat_#{version}_linux_amd64.tar.gz"
      sha256 "433064dfff0cc526fa7891c0278c650a848f1df4165fe740c26b8770e62cf70e"
    end
    on_arm do
      url "https://github.com/Eagle-Konbu/sanat/releases/download/v#{version}/sanat_#{version}_linux_arm64.tar.gz"
      sha256 "d3421bdd89f7b782ca2ac10eec8154cf491726a38c3e78e2623497bca7e74978"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sanat"]
    end
  end

  # No zap stanza required
end
