# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Catalyst < Formula
  desc "CLI tool for controlling Nature Remo devices"
  homepage "https://github.com/Eagle-Konbu/catalyst"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Eagle-Konbu/catalyst/releases/download/v0.1.0/catalyst_0.1.0_darwin_amd64.tar.gz"
      sha256 "0901a453b7af5abd4f998ed01fc757cfe24a7e78bf91d5eb796cf5d07dec3ae2"

      def install
        bin.install "catalyst"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Eagle-Konbu/catalyst/releases/download/v0.1.0/catalyst_0.1.0_darwin_arm64.tar.gz"
      sha256 "7b8c900a9d49b80db6c9ecf6ab2fd1674b7302d6ba096e850c657ac2f9e2ec97"

      def install
        bin.install "catalyst"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Eagle-Konbu/catalyst/releases/download/v0.1.0/catalyst_0.1.0_linux_amd64.tar.gz"
      sha256 "71155e04b817b178b6f2e060ce128b32eaa885ee14d3a2a5b463ab4ad778c6a8"
      def install
        bin.install "catalyst"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Eagle-Konbu/catalyst/releases/download/v0.1.0/catalyst_0.1.0_linux_arm64.tar.gz"
      sha256 "d2f54d1cdefe1c1a5364d426d9876564af5ef491113f079c249c550d386abc6d"
      def install
        bin.install "catalyst"
      end
    end
  end

  test do
    system "#{bin}/catalyst", "--help"T
  end
end
